---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persitent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: local
  storageClassName: hostpath
